### ISSUE TITLE
object properties not callable when from magic methods?

### ISSUE THREAD

**Issue by owzim** [marcostoll/processwire-template-twig-replace#7]
I get the following issue when calling properties on some PW objects like page:

in PHP

```PHP
$page->template->name
```

in Twig, that does not work:

```JS
page.template.name
```

throws:
```
Fatal error: Exception: An exception has been thrown during the rendering of a template ("Method Page::template does not exist or is not callable in this context")
```

This however works:
```JS
page.get('template').get('name')
```

I guess this has something to do with the fact that those properties are added dynamically (internally stored in the data array/object, and set/get via magic methods)

How to fix this?

**Comment by owzim** [comment]
This has been partly fixed, see https://github.com/ryancramerdesign/ProcessWire/issues/900

**Comment by felixwahner** [comment]
I'm closing this then.
